default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: formapp_development

test:
  <<: *default
  database: formapp_test

production:
  <<: *default
  database: formapp_production
  username: formapp
  password: <%= ENV['FORMAPP_DATABASE_PASSWORD'] %>
